DaiDomivky/DaiDomivky/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework.permissions import AllowAny

app_name = 'home'

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.myapi.com/policies/terms/",
        contact=openapi.Contact(email="contact@myapi.com"),
        license=openapi.License(name="Test License"),
    ),
    public=True,
    permission_classes=(AllowAny,),
)

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

DaiDomivky/api/urls.py
from django.urls import include, path

urlpatterns = [

    path('eshop/', include('apps.eshop.urls')),
    path('blog/', include('apps.blog.urls')),
    path('user/', include('apps.user.urls')),
    path('', include('apps.home.urls')),
]

DaiDomivky/apps/eshop/urls.py
from django.urls import path

from .views import OrderDetail, OrderItemCreate, OrdersHistoryList, PaymentAndShipmentCreate, PaymentUpdate, \
    ProductDetail, ProductList, ShipmentUpdate

app_name = 'eshop'

urlpatterns = [
    path('', ProductList.as_view(), name='product_list'),
    path('<int:pk>/', ProductDetail.as_view(), name='product_detail'),
    path('orderitem_create/', OrderItemCreate.as_view(), name='order_item_create'),
    path('order_detail/<int:pk>/', OrderDetail.as_view(), name='order_active'),
    path('order_history/', OrdersHistoryList.as_view(), name='order_history'),
    path('payment_update/<int:pk>/', PaymentUpdate.as_view(), name='payment_update'),
    path('shipment_update/<int:pk>/', ShipmentUpdate.as_view(), name='shipment_update'),
    path('checkout_create/', PaymentAndShipmentCreate.as_view(), name='checkout_create'),
]

DaiDomivky/apps/home/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.Index.as_view())
]

DaiDomivky/apps/home/models.py
from django.db import models

# Create your models here.

DaiDomivky/apps/home/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View


# Create your views here.


# def index(request):
#     return render(request, 'home/index.html')
#

class Index(View):
    def get(self, request):
        return render(request, 'home/index.html')

DaiDomivky/apps/home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway:400,600,700&amp;display=swap&amp;subset=latin-ext"
          media="all">
{% endblock %}
{% block title %}
    Test
{% endblock %}

{% block content %}
    <header class="header">
        <nav class="navbar">
            <div class="logo-container">
                <a href="">
                    <img src="" alt="logo">

                </a>
            </div>
            <ul class="nav-list">
                <li>
                    <a class='nav-list-link' href="">Про нас</a>
                </li>
                <li>
                    <a class='nav-list-link' href="{% url 'blog:list' %}">Блог</a>
                </li>
                <li>
                    <a class='nav-list-link' href="">Кампанії</a>
                </li>
                <li>
                    <a class='nav-list-link' href="">Підтримати організацію</a>
                </li>
                <li>
                    <a class='nav-list-link' href="{% url 'eshop:product_list' %}">Мерч</a>
                </li>
                <li>
                    <a class='nav-list-link' href="">Контакти</a>
                </li>
                <li>
                    <a href="">
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="heart" role="img"
                             xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
                             class="fs-s mr-10 svg-inline--fa fa-heart fa-w-16 heart" data-v-4180a957="">
                            <path fill="currentColor"
                                  d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"
                                  data-v-4180a957="" class=""></path>
                        </svg>
                        Підтримати</a>
                </li>
            </ul>
            <div class="nav-toggle">
                <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="bars" role="img"
                     xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="burger-icon">
                    <path fill="currentColor"
                          d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"
                          class="">
                    </path>
                </svg>
            </div>
        </nav>
        <div class="text-content">
            <h1>Допоможи нам<br>
                <span>Допомогти тваринам знайти дім</span>
            </h1>
            <div class="learn-more">
                <a class="learn-more-link" href="">Дізнатися більше →</a>
            </div>
        </div>
    </header>
    <section class="section">
        <div class="container">
            <h2>Час змін!</h2>
            <div class="row">
                <div class="content">
                    <h3>
                        <span>Щороку тисячі тварин <br> народжуються та помирають на<br> вулицях</span>
                    </h3>
                    <a href="https://www.youtube.com/watch?v=XvjMJqpl4EY&ab_channel=2berega" target="_blank"
                       rel="noreferrer"
                       class="video-link">
                        <div class="icon-wrap">
                            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="play" role="img"
                                 xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"
                                 class="fs-xs svg-inline--fa fa-play fa-w-14">
                                <path fill="currentColor"
                                      d="M424.4 214.7L72.4 6.6C43.8-10.3 0 6.1 0 47.9V464c0 37.5 40.7 60.1 72.4 41.3l352-208c31.4-18.5 31.5-64.1 0-82.6z"
                                      class=""></path>
                            </svg>
                        </div>
                        <div class="uppercase"><p>Дивитись<br>
                            <span class="cl-primary">відео про життя тварин на вулиці</span></p>
                        </div>
                    </a>
                    <div class="h3">
                        <p>Допоможіть нам змінити долю безхатніх тварин.<br> Ще не придумав<br> бла бла бла.</p>
                    </div>
                    <div class="button-link">
                        <div class="link"><!----><a href="https://cagefree.opencages.com.ua/"
                                                    id="hero-cta-cagefreeopencagescomua" target="_blank"
                                                    rel="noreferrer" class="btn-cta dark">Підпишіть петицію</a></div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/index.js' %}">
    $(document).ready(function() {
    $('.learn-more-link').click(function(e) {
        e.preventDefault(); // prevent the default action
        $('html, body').animate({
            scrollTop: $($(this).attr('href')).offset().top
        }, 'slow');
    });
});
    </script>
{% endblock %}