DaiDomivky/DaiDomivky/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from drf_yasg import openapi
from drf_yasg.views import get_schema_view

from rest_framework.permissions import AllowAny

app_name = 'home'

schema_view = get_schema_view(
    openapi.Info(
        title="My API",
        default_version='v1',
        description="API description",
        terms_of_service="https://www.myapi.com/policies/terms/",
        contact=openapi.Contact(email="contact@myapi.com"),
        license=openapi.License(name="Test License"),
    ),
    public=True,
    permission_classes=(AllowAny,),
)

urlpatterns = [
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

DaiDomivky/api/urls.py
from django.urls import include, path

urlpatterns = [

    path('eshop/', include('apps.eshop.urls')),
    path('blog/', include('apps.blog.urls')),
    path('user/', include('apps.user.urls')),
    path('', include('apps.home.urls')),
]

DaiDomivky/apps/blog/urls.py
from django.urls import path

from .views import PostCreateView, PostDetailView, PostListView, PostUpdateView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='list'),  # name = blog:list
    path('<slug:slug_param>', PostDetailView.as_view(), name='detail'),  # name = blog:detail
    path('create/', PostCreateView.as_view(), name='create'),
    path('<slug:slug_param>/update/', PostUpdateView.as_view(), name='update')
]

DaiDomivky/apps/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import SignUpView, UserLoginView


app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='blog:list'), name='logout')
]

DaiDomivky/apps/blog/models.py
from DaiDomivky.settings import AUTH_USER_MODEL

from django.db import models
from django.urls import reverse


class Post(models.Model):
    STATUS = ((0, 'Draft'),
              (1, 'Published'))

    title = models.CharField(max_length=200, unique=True, help_text='Title for post')
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField(help_text='Content for post')
    status = models.IntegerField(choices=STATUS, default=0)
    image = models.ImageField(upload_to='images', null=True, blank=True)

    def get_absolute_url(self):
        return reverse('blog:detail', args=(self.slug,))

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.title} by {self.author}"

DaiDomivky/apps/blog/views.py
from DaiDomivky.constants import StatusType
from DaiDomivky.mixins import PermissionHandlerMixin, SlugifyMixin

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView


from .models import Post


class PostListView(ListView):
    """
    View for displaying a list of blog posts.
    """
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'list'
    paginate_by = 4

    def get_queryset(self):
        """
        Returns the queryset of blog posts.
        - Retrieves the origin queryset and fetches related 'author' objects with .select_related('author').
        - Filters the posts based on the user's authentication status and post status.
        - Returns the filtered queryset.
        """
        post_qs = super().get_queryset().select_related('author')

        if self.request.user.is_authenticated:
            # Retrieve all published posts or unpublished posts authored by the current user
            post_qs = post_qs.filter(
                Q(status=StatusType.PUBLISHED) | Q(author=self.request.user, status=StatusType.DRAFT))
        else:
            post_qs = post_qs.filter(status=StatusType.PUBLISHED)

        return post_qs


class PostDetailView(DetailView):
    """
    View for displaying a single blog post in detail.
    """
    model = Post
    template_name = 'blog/post_detail.html'
    slug_url_kwarg = 'slug_param'
    context_object_name = 'post'

    def get_object(self, queryset=None):
        """
        Retrieves the blog post object.
        """
        post_obj = super().get_object()
        if post_obj.status == StatusType.DRAFT and self.request.user != post_obj.author:
            raise Http404("Post not found.")
        return post_obj

    def get_context_data(self, **kwargs):
        """
        Adds additional context data to the view.
        """
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class PostCreateView(PermissionHandlerMixin, SlugifyMixin, LoginRequiredMixin, CreateView):
    """
    View for creating a new blog post.
    """
    model = Post
    template_name = 'blog/post_create.html'
    fields = ['title', 'content', 'status']

    def get_success_url(self):
        """
        Returns the URL to redirect to upon successful post creation.
        """
        return reverse_lazy('blog:list')


class PostUpdateView(PermissionHandlerMixin, SlugifyMixin, LoginRequiredMixin, UpdateView):
    """
    View for updating an existing blog post.
    """
    model = Post
    template_name = 'blog/post_update.html'
    slug_url_kwarg = 'slug_param'
    fields = ['title', 'content', 'status']

    def get_success_url(self):
        """
        Returns the URL to redirect to upon successful post update.
        """
        return self.object.get_absolute_url()

DaiDomivky/apps/blog/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}



{% block content %}
    {% if not user.is_authenticated %}
        <a href="{% url 'user:login' %}">Login</a>
        <a href="{% url 'user:signup' %}">Sign Up</a>
    {% endif %}
    {% if user.is_authenticated %}
        <a href={% url 'user:logout' %}>Logout</a>
        <a href={% url 'blog:create' %}>Create</a>
    {% endif %}
    {% for post in list %}
        <ul style="list-style-type: none">
            <li>
                <a href= {{ post.get_absolute_url }}>{{ post }} {{ post.status }}</a>
            </li>
        </ul>
    {% endfor %}

    <div>
        <ul style="list-style-type: none; margin: 0; padding: 0; display: flex;">
            {% for p in paginator.page_range %}
                <li style="margin-right: 10px;">
                    <a href="?page={{ p }}">{{ p }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

DaiDomivky/apps/blog/templates/blog/post_create.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}



{% block content %}
    <h2>Create new post</h2>
    <form method = 'post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
    </form>

{% endblock %}

DaiDomivky/apps/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}



{% block content %}
    <div>{% if post.author == user %}
        <a href="{% url 'blog:update'  post.slug %}">Update</a>
    {% endif %}
        <ul style="list-style-type: none">
            <li>
                {{ post.title }}
            </li>
            <li>
                {{ post.content }}
            </li>
            <li>
                {{ post.author }}
            </li>
        </ul>
    </div>

{% endblock %}

DaiDomivky/apps/blog/templates/blog/post_update.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}



{% block content %}
    <h2>Update your post</h2>
    <form method = 'post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
    </form>

{% endblock %}